security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\Users
                property: user_name
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            pattern:    ^/
            provider: db_provider
            form_login:
                username_parameter: '_username'
                login_path: login
                check_path: login
            anonymous: true




            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/, roles: ROLE_USER }
