#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\ProductController::getProductList

product_preview:
  path: /product-preview/{id}
  controller: App\Controller\ProductController::getProductPreview

add_basket:
  path: /basket/{id}
  controller: App\Controller\BasketController::addProductBasket

basket:
  path: /basket
  controller: App\Controller\BasketController::getBasketProducts

delete_product_basket:
  path: /basket/delete/{id}
  controller: App\Controller\BasketController::deleteProductBasket

sign_up:
  path: /sign-up
  controller: App\controller\UsersController::createRegistrationForm

profile:
  path: /profile
  controller: App\Controller\AddProductController::addProduct


