#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\ProductListController::getProductList

product_preview:
  path: /product-preview/{id}
  controller: App\Controller\ProductPreviewController::getProductPreview