#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\ProductController::getProductList

product_preview:
  path: /product-preview/{id}
  controller: App\Controller\ProductController::getProductPreview

add_basket:
  path: /basket/{id}
  controller: App\Controller\BasketController::addProductBasket

basket:
  path: /basket
  controller: App\Controller\BasketController::getBasketProducts

delete_product_basket:
  path: /basket/delete/{id}
  controller: App\Controller\BasketController::deleteProductBasket

admin:
  path: /admin
  controller: App\Controller\UsersController::admin

profile:
  path: /profile
  controller: App\Controller\ProfileController::addProduct

profile_edit:
  path: /profile/edit-product/{id}
  controller: App\Controller\ProfileController::editProduct

profile_edit_delete_image:
  path: /profile/delete-image/{id}
  controller: App\Controller\ProfileController::deleteProductImage

profile_delete:
  path: /profile/delete/{id}
  controller: App\Controller\ProfileController::deleteProduct

login:
  path: /login
  controller: App\Controller\SecurityController::login

reistration:
  path: /registration
  controller: App\Controller\RegistrationController::register



